package org.popcraft.bolt.util;

/**
 * Separates player inventory permissions from automated item transport permissions.
 * Every InventoryMoveItemEvent is generated by an automated source, so a protected
 * destination and source use independent insert/extract permissions.
 */
public final class InventoryTransportPolicy {
    private InventoryTransportPolicy() {
    }

    public static String sourcePermission() {
        return Permission.HOPPER_EXTRACT;
    }

    public static String destinationPermission() {
        return Permission.HOPPER_INSERT;
    }
}
