access_list_entry= * <source_identifier> (<source_type>: <access_type>)
access_list_entry_default= * <source_identifier> (<source_type>)
callback_expired=<red>此指令已過期。</red>
cleanup_start=正在開始清理 <yellow><count></yellow> 個保護區域。這可能需要一些時間。
cleanup_remove=正在移除無效的保護區域：<raw_protection>
cleanup_complete=已在 <yellow><seconds></yellow> 秒內完成 <yellow><count></yellow> 個保護區域的清理！
click_action=點擊目標以進行 <action>。
click_edited=已編輯 <yellow><protection_type></yellow> <yellow><protection></yellow>。
click_edited_no_owner=您不擁有這個保護區域！
click_edited_no_permission=您沒有編輯此保護區域的權限！
click_info=點擊保護區域以查看資訊。
click_locked=已鎖定 <yellow><protection_type></yellow> <yellow><protection></yellow>。
click_locked_no_exist=保護類型 <yellow><protection_type></yellow> 不存在。
click_locked_no_permission=您沒有使用該保護類型的權限！
click_locked_cancelled=您不被允許鎖定此 <yellow><protection></yellow>。
click_locked_already=此 <yellow><protection></yellow> 已被鎖定。
click_locked_changed=已將保護類型更改為 <yellow><protection_type></yellow>。
click_not_locked=此 <yellow><protection></yellow> 尚未被鎖定。
click_not_lockable=此 <yellow><protection></yellow> 無法被鎖定。
click_transfer=點擊保護區域以進行轉移。
click_transfer_all=已將 <yellow><old_player></yellow> 的所有保護區域轉移給 <yellow><new_player></yellow>。
click_transfer_confirm=已將 <yellow><protection_type></yellow> <yellow><protection></yellow> 轉移給 <yellow><player></yellow>。
click_unlocked=已解鎖 <yellow><protection_type></yellow> <yellow><protection></yellow>。
click_unlocked_no_permission=您沒有解鎖此保護區域的權限！
command_invalid=該指令不存在！
command_no_permission=<red>您沒有使用此指令的權限。</red>
command_not_enough_args=執行此指令所需的參數不足。
command_player_only=此指令只能由玩家使用。
edit=編輯
edit_access_invalid=存取權限類型 <yellow><access_type></yellow> 無效。
edit_access_no_permission=您沒有使用該存取權限類型的權限！
edit_source_invalid=來源類型 <yellow><source_type></yellow> 無效。
edit_source_no_permission=您沒有使用該來源類型的權限！
enter_password=密碼正確。
enter_password_none=<red>您需要輸入密碼！</red>
expire_complete=已移除 <yellow><count></yellow> 個保護區域！
expire_invalid_time=<red>您需要輸入有效的時間！</red>
find_distance=距離 <number> 個方塊
find_header=找到結果：
find_header_new=顯示第 <yellow><first></yellow> - <yellow><last></yellow> 項結果，共 <yellow><count></yellow> 項：
find_result=<yellow><protection_type></yellow> <yellow><protection></yellow> 已由 <yellow><player></yellow> 於 <yellow><time></yellow> 鎖定<newline><command><gray>位於 <world> 的 <x>, <y>, <z></gray></command>
find_result_unknown=<yellow><protection_type></yellow> <yellow><protection></yellow> 已由 <yellow><player></yellow> 於 <yellow><time></yellow> 鎖定<newline><gray>位置未知，<protection> 未載入</gray>
find_teleport=點擊以傳送
find_next=點擊以查看更多
find_next_new=[<pages> ... <page>]
find_next_new_page_current=<yellow> <page> </yellow>
find_next_new_page_other=<white> <page> </white>
find_next_new_page_separator=|
find_none=無
flush=正在將保護區域更新寫入資料庫 (<count>)
generic_not_found=<red>找不到 <yellow><x></yellow>。</red>
group_already_exists=群組 <yellow><group></yellow> 已經存在！
group_created=已建立群組 <yellow><group></yellow>。
group_deleted=已刪除群組 <yellow><group></yellow>。
group_doesnt_exist=群組 <yellow><group></yellow> 不存在！
group_list_members=群組 <yellow><group></yellow> 的成員：<group_members>
group_not_owner=您不擁有群組 <yellow><group></yellow>。
group_player_add=已將 <yellow><player></yellow> 加入群組 <yellow><group></yellow>。
group_player_remove=已將 <yellow><player></yellow> 從群組 <yellow><group></yellow> 中移除。
info=<protection_type> <protection>\n擁有者：<yellow><player></yellow>
info_full_access=<protection_type> <protection>\n擁有者：<yellow><player></yellow>\n建立時間：<yellow><created_time></yellow>\n最後存取時間：<yellow><accessed_time></yellow>\n存取清單 (<yellow><access_list_size></yellow>)：\n<access_list>
info_full_no_access=<protection_type> <protection>\n擁有者：<yellow><player></yellow>\n建立時間：<yellow><created_time></yellow>\n最後存取時間：<yellow><accessed_time></yellow>
info_self=存取清單 (<yellow><access_list_size></yellow>)：\n<access_list>
lock=鎖定
locked=此 <yellow><protection></yellow> 已被魔法咒語鎖定。
migration_completed=保護區域轉移成功！
migration_completed_found_entities=偵測到來自 LWC 的實體保護區域！您是否也想嘗試轉換這些資料？這可能需要一些時間，具體取決於您的地圖大小。請輸入「<yellow><command></yellow>」以確認。
migration_in_progress=資料轉移已在進行中，請稍候！
migration_lwc_missing=在進行資料轉移前，您必須先安裝 LWC！
migration_started=已開始將資料從 <yellow><old_plugin></yellow> 轉移至 <yellow><new_plugin></yellow>...
mode_disabled=已停用 <yellow><mode></yellow> 模式。
mode_enabled=已啟用 <yellow><mode></yellow> 模式。
mode_invalid=該模式無效！
player_not_found=<red>找不到玩家 <yellow><player></yellow>。</red>
protection_notify=此 <yellow><protection_type></yellow> <yellow><protection></yellow> 已由 <yellow><player></yellow> 鎖定。
protection_notify_generic=此 <yellow><protection_type></yellow> <yellow><protection></yellow> 已被鎖定。
purge=已移除 <yellow><player></yellow> 擁有的所有保護區域。
reload=設定檔已重新載入！
status=資料庫狀態\n受保護方塊數：<count_blocks>\n受保護實體數：<count_entities>
storage_export_exists=<red>資料庫匯出檔已存在，可能已有匯出程序正在進行中。</red>
storage_export_started=已開始匯出...
storage_export_completed=匯出成功建立！
storage_import_doesnt_exist=<red>尚未建立任何資料庫匯出檔。</red>
storage_import_started=已開始匯入...
storage_import_completed=匯入已成功完成！
storage_in_progress=<red>已有匯出或匯入程序正在進行中。</red>
time_ago=<time> 前
time_seconds=<number>秒
time_minutes=<number>分
time_hours=<number>小時
time_days=<number>天
time_months=<number>個月
time_years=<number>年
trust=請使用指令「<yellow><command></yellow>」編輯您的信任存取清單。完成後，請輸入「<yellow><command_2></yellow>」進行確認。請注意，受信任的對象將能夠存取您的<red>所有</red>保護區域！
trust_add=正在新增 <source_type> <source_identifier>。
trust_remove=正在移除 <source_type> <source_identifier>。
trust_confirm=受信任的對象將能夠存取您的所有保護區域。如果您確定要執行此操作，請輸入「<yellow><command></yellow>」。
trust_edited=已編輯信任存取清單。
trust_edited_failed=請使用「<yellow><command></yellow>」來修改您的信任存取清單！
unknown=未知
unlock=解鎖
you=您
mode_persist=持續
mode_nolock=不鎖定
mode_nospam=不洗版
protection_type_private=私人
protection_type_display=展示
protection_type_deposit=僅存入
protection_type_withdrawal=僅取出
protection_type_public=公共
protection_type_redstone=紅石
protection_type_autoclose=自動關閉
access_type_normal=一般
access_type_admin=管理員
access_type_autoclose=自動關閉
source_type_player=玩家
source_type_password=密碼
source_type_permission=權限
source_type_group=群組
source_type_redstone=紅石
source_type_block=方塊
source_type_door=門
source_type_region=區域
source_type_town=城鎮
source_type_faction=陣營
source_type_entity=實體
help_command_short_admin_cleanup=<command>
help_command_short_admin=<command>
help_command_short_admin_convert=<command>
help_command_short_admin_debug=<command>
help_command_short_admin_expire=<command> <時間> (秒|分|小時|天)
help_command_short_admin_find=<command> <玩家>
help_command_short_admin_flush=<command>
help_command_short_admin_nearby=<command> <半徑>
help_command_short_admin_purge=<command> <玩家>
help_command_short_admin_reload=<command>
help_command_short_admin_report=<command> <字面值>
help_command_short_admin_storage=<command> <字面值>
help_command_short_admin_transfer=<command> <玩家> [轉移給]
help_command_short_admin_trust=<command> <玩家> <字面值>
help_command_short_edit=<command> <字面值> <玩家>
help_command_short_modify=<command> <字面值> <存取權限> <來源類型> <來源...>
help_command_short_group=<command> <字面值> <群組> [玩家...]
help_command_short_help=<command> <子指令>
help_command_short_info=<command>
help_command_short_lock=<command> [類型]
help_command_short_mode=<command> <模式>
help_command_short_password=<command> <密碼>
help_command_short_transfer=<command> <玩家>
help_command_short_trust=<command> <字面值>
help_command_short_unlock=<command>
help_command_long_admin_cleanup=清理資料庫中在遊戲世界裡已不存在的保護區域。例如：使用 WorldEdit 等其他外掛在未破壞方塊的情況下直接移除方塊時，就可能會發生這種情況。
help_command_long_admin=提供管理員工具，用於管理 Bolt 資料庫和玩家。
help_command_long_admin_convert=將現有的 LWC 資料庫轉換為 Bolt。請參閱 Wiki 了解有關資料轉移的資訊。
help_command_long_admin_debug=顯示技術性的保護資訊。
help_command_long_admin_expire=移除已有一段時間未被存取的保護區域。
help_command_long_admin_find=尋找指定玩家的保護區域。
help_command_long_admin_flush=立即將保護區域更新寫入資料庫。
help_command_long_admin_nearby=尋找指定半徑內的保護區域。
help_command_long_admin_purge=移除指定玩家的所有保護區域。
help_command_long_admin_reload=強制完全重新載入 Bolt 的設定檔、重新載入翻譯，並更新保護類型、存取類型和保護比對器。
help_command_long_admin_storage=匯出或匯入 Bolt 資料，以在不同資料庫之間進行轉換。
help_command_long_admin_report=顯示有關保護事件觸發器與快取命中/未命中的技術資訊。
help_command_long_admin_transfer=強制將一個保護區域轉移給指定玩家，或將某玩家的所有保護區域轉移給另一名玩家。
help_command_long_admin_trust=檢視或修改某人的信任存取清單。
help_command_long_edit=新增或移除保護區域存取控制清單 (ACL) 中的玩家。
help_command_long_modify=在保護區域存取控制清單 (ACL) 中新增或移除具有指定權限的來源。
help_command_long_group=管理自訂玩家群組，這些群組可用於存取控制清單 (ACL)。
help_command_long_help=顯示指令說明。
help_command_long_info=顯示保護區域資訊。
help_command_long_lock=鎖定目標。可選擇提供鎖定採用的保護類型（預設為私人）。
help_command_long_mode=切換玩家模式。例如：持續、不鎖定、不洗版。
help_command_long_password=為已新增密碼來源的保護區域輸入密碼。
help_command_long_transfer=將您擁有的保護區域轉移給另一名玩家。
help_command_long_trust=提示、列出或確認對您信任存取清單的變更。
help_command_long_unlock=解鎖目標。