以下為翻譯後的繁體中文版本：

access_list_entry= * <source_identifier> (<source_type>: <access_type>)
access_list_entry_default= * <source_identifier> (<source_type>)
callback_expired=<red>此指令已過期。</red>
cleanup_start=正在開始清理 <yellow><count></yellow> 個保護。這可能需要一些時間。
cleanup_remove=正在移除無效保護：<raw_protection>
cleanup_complete=已完成清理 <yellow><count></yellow> 個保護，耗時 <yellow><seconds></yellow> 秒！
click_action=點擊某個物品以進行 <action>。
click_edited=已編輯 <yellow><protection_type></yellow> <yellow><protection></yellow>。
click_edited_no_owner=你不擁有此保護！
click_edited_no_permission=你沒有編輯此保護的權限！
click_info=點擊一個保護以查看資訊。
click_locked=已鎖定 <yellow><protection_type></yellow> <yellow><protection></yellow>。
click_locked_no_exist=保護類型 <protection_type> 不存在。
click_locked_no_permission=你沒有使用該保護類型的權限！
click_locked_cancelled=你不被允許鎖定此 <yellow><protection></yellow>。
click_locked_already=此 <yellow><protection></yellow> 已經被鎖定。
click_locked_changed=已將保護類型更改為 <yellow><protection_type></yellow>。
click_not_locked=此 <yellow><protection></yellow> 並未被鎖定。
click_not_lockable=此 <yellow><protection></yellow> 無法被鎖定。
click_transfer=點擊一個保護以進行轉移。
click_transfer_all=已將所有來自 <old_player> 的保護轉移給 <new_player>。
click_transfer_confirm=已將 <yellow><protection_type></yellow> <yellow><protection></yellow> 轉移給 <yellow><player></yellow>。
click_unlocked=已解鎖 <yellow><protection_type></yellow> <yellow><protection></yellow>。
click_unlocked_no_permission=你沒有解鎖此保護的權限！
command_invalid=該指令不存在！
command_no_permission=<red>你沒有執行此指令的權限。</red>
command_not_enough_args=執行此指令所需的參數不足。
command_player_only=此指令僅能由玩家使用。
edit=編輯
edit_access_invalid=訪問類型 <yellow><access_type></yellow> 無效。
edit_access_no_permission=你沒有使用該訪問類型的權限！
edit_source_invalid=來源類型 <yellow><source_type></yellow> 無效。
edit_source_no_permission=你沒有使用該來源類型的權限！
enter_password=密碼已接受。
enter_password_none=<red>你需要輸入密碼！</red>
expire_complete=已移除 <yellow><count></yellow> 個保護！
expire_invalid_time=<red>你需要輸入一個有效的時間！</red>
find_distance=距離 <number> 個方塊
find_header=搜尋結果：
find_header_new=正在顯示結果 <yellow><first></yellow> - <yellow><last></yellow>（共 <yellow><count></yellow> 筆）：
find_result=<yellow><protection_type></yellow> <yellow><protection></yellow>，由 <yellow><player></yellow> 於 <yellow><time></yellow> 鎖定<newline><command><gray>位於 <world> 的 <x>, <y>, <z></gray></command>
find_result_unknown=<yellow><protection_type></yellow> <yellow><protection></yellow>，由 <yellow><player></yellow> 於 <yellow><time></yellow> 鎖定<newline><gray>位置未知，<protection> 未載入</gray>
find_teleport=點擊以傳送
find_next=點擊以查看更多
find_next_new=[<pages> ... <page>]
find_next_new_page_current=<yellow> <page> </yellow>
find_next_new_page_other=<white> <page> </white>
find_next_new_page_separator=|
find_none=無
flush=正在刷新保護更新 (<count>)
generic_not_found=<red>找不到 <yellow><x></yellow>。</red>
group_already_exists=群組 <yellow><group></yellow> 已存在！
group_created=已創建群組 <yellow><group></yellow>。
group_deleted=已刪除群組 <yellow><group></yellow>。
group_doesnt_exist=群組 <yellow><group></yellow> 不存在！
group_list_members=群組 <yellow><group></yellow> 的成員：<group_members>
group_not_owner=你不擁有群組 <yellow><group></yellow>。
group_player_add=已將 <yellow><player></yellow> 加入群組 <yellow><group></yellow>。
group_player_remove=已將 <yellow><player></yellow> 從群組 <yellow><group></yellow> 移除。
info=<protection_type> <protection>\n擁有者：<yellow><player></yellow>
info_full_access=<protection_type> <protection>\n擁有者：<yellow><player></yellow>\n創建於：<yellow><created_time></yellow>\n最後存取：<yellow><accessed_time></yellow>\n訪問列表 (<yellow><access_list_size></yellow>)：\n<access_list>
info_full_no_access=<protection_type> <protection>\n擁有者：<yellow><player></yellow>\n創建於：<yellow><created_time></yellow>\n最後存取：<yellow><accessed_time></yellow>
info_self=訪問列表 (<access_list_size>)：\n<access_list>
lock=鎖定
locked=此 <yellow><protection></yellow> 已被魔法咒語鎖定。
migration_completed=保護轉移成功！
migration_completed_found_entities=偵測到來自 LWC 的實體保護！是否也要嘗試轉換這些保護？根據你的世界大小，這可能需要一些時間。輸入「<yellow><command></yellow>」以確認。
migration_in_progress=遷移作業進行中，請稍候！
migration_lwc_missing=你必須先安裝 LWC 才能進行遷移！
migration_started=開始將 <old_plugin> 遷移至 <new_plugin>...
mode_disabled=已停用 <yellow><mode></yellow> 模式。
mode_enabled=已啟用 <yellow><mode></yellow> 模式。
mode_invalid=這不是有效的模式！
player_not_found=<red>找不到玩家 <yellow><player></yellow>。</red>
protection_notify=此 <yellow><protection_type></yellow> <yellow><protection></yellow> 由 <yellow><player></yellow> 鎖定。
protection_notify_generic=此 <yellow><protection_type></yellow> <yellow><protection></yellow> 已被鎖定。
purge=已移除由 <yellow><player></yellow> 擁有的所有保護。
reload=設定已重新載入！
status=資料庫狀態\n受保護方塊：<count_blocks>\n受保護實體：<count_entities>
storage_export_exists=資料庫匯出檔案已存在，可能已有匯出作業在進行中。
storage_export_started=開始匯出...
storage_export_completed=匯出成功建立！
storage_import_doesnt_exist=尚未建立任何資料庫匯出檔。
storage_import_started=開始匯入...
storage_import_completed=匯入成功完成！
storage_in_progress=已有匯出或匯入作業在進行中。
time_ago=<time> 前
time_seconds=<number>秒
time_minutes=<number>分
time_hours=<number>時
time_days=<number>天
time_months=<number>個月
time_years=<number>年
trust=使用「<yellow><command></yellow>」編輯你的信任訪問列表。完成後，輸入「<yellow><command_2></yellow>」進行確認。請注意，受信任的來源能夠存取你的 <red>所有</red> 保護！
trust_add=正在新增 <source_type> <source_identifier>。
trust_remove=正在移除 <source_type> <source_identifier>。
trust_confirm=受信任的來源將能存取你所有的保護。如果你確定要這麼做，請輸入「<yellow><command></yellow>」。
trust_edited=已編輯信任訪問列表。
trust_edited_failed=使用「<yellow><command></yellow>」來變更你的信任訪問列表！
unknown=未知
unlock=解鎖
you=你
mode_persist=持久 (Persist)
mode_nolock=不鎖定 (No Lock)
mode_nospam=防洗頻 (No Spam)
protection_type_private=私人 (Private)
protection_type_display=展示 (Display)
protection_type_deposit=存入 (Deposit)
protection_type_withdrawal=提取 (Withdrawal)
protection_type_public=公開 (Public)
protection_type_redstone=紅石 (Redstone)
protection_type_autoclose=自動關閉 (Auto Close)
access_type_normal=一般 (Normal)
access_type_admin=管理員 (Admin)
access_type_autoclose=自動關閉 (Auto Close)
source_type_player=玩家 (Player)
source_type_password=密碼 (Password)
source_type_permission=權限 (Permission)
source_type_group=群組 (Group)
source_type_redstone=紅石 (Redstone)
source_type_block=方塊 (Block)
source_type_door=門 (Door)
source_type_region=區域 (Region)
source_type_town=城鎮 (Town)
source_type_faction=陣營 (Faction)
source_type_entity=實體 (Entity)
help_command_short_admin_cleanup=<command>
help_command_short_admin=<command>
help_command_short_admin_convert=<command>
help_command_short_admin_debug=<command>
help_command_short_admin_expire=<command> <time> (秒|分|時|天)
help_command_short_admin_find=<command> <player>
help_command_short_admin_flush=<command>
help_command_short_admin_nearby=<command> <radius>
help_command_short_admin_purge=<command> <player>
help_command_short_admin_reload=<command>
help_command_short_admin_report=<command> <literal>
help_command_short_admin_storage=<command> <literal>
help_command_short_admin_transfer=<command> <player> [到]
help_command_short_admin_trust=<command> <player> <literal>
help_command_short_edit=<command> <literal> <player>
help_command_short_modify=<command> <literal> <access> <source-type> <sources...>
help_command_short_group=<command> <literal> <group> [玩家...]
help_command_short_help=<command> <subcommand>
help_command_short_info=<command>
help_command_short_lock=<command> [類型]
help_command_short_mode=<command> <mode>
help_command_short_password=<command> <password>
help_command_short_transfer=<command> <player>
help_command_short_trust=<command> <literal>
help_command_short_unlock=<command>
help_command_long_admin_cleanup=清理資料庫中在遊戲世界中已不存在的保護。例如，使用 WorldEdit 等其他插件移除方塊而未觸發破壞時，可能會發生這種情況。
help_command_long_admin=提供管理 Bolt 資料庫與玩家的管理員工具。
help_command_long_admin_convert=將現有的 LWC 資料庫轉換為 Bolt。請參閱維基關於遷移的說明。
help_command_long_admin_debug=顯示技術性保護資訊。
help_command_long_admin_expire=移除一段時間未被存取的保護。
help_command_long_admin_find=尋找特定玩家的保護。
help_command_long_admin_flush=立即將保護更新刷新至資料庫。
help_command_long_admin_nearby=在給定半徑內搜尋保護。
help_command_long_admin_purge=移除指定玩家的所有保護。
help_command_long_admin_reload=強制完整重新載入 Bolt 設定、重新載入翻譯，並更新保護類型、訪問類型與保護匹配器。
help_command_long_admin_storage=匯出或匯入 Bolt 資料以在不同資料庫間進行轉換。
help_command_long_admin_report=顯示有關保護事件觸發與快取命中/未命中的技術資訊。
help_command_long_admin_transfer=強制將保護轉移給指定玩家，或是將該玩家的所有保護轉移給另一名玩家。
help_command_long_admin_trust=查看或修改某人的信任訪問列表。
help_command_long_edit=在保護的訪問列表 (ACL) 中新增或移除玩家。
help_command_long_modify=在保護的訪問列表 (ACL) 中新增或移除具有特定訪問權限的來源。
help_command_long_group=管理可用於訪問列表 (ACL) 的自訂玩家群組。
help_command_long_help=顯示指令說明。
help_command_long_info=顯示保護資訊。
help_command_long_lock=鎖定物品。可選填保護類型進行鎖定（預設為私人）。
help_command_long_mode=切換玩家模式。例如：持久 (persist)、不鎖定 (no lock)、防洗頻 (no spam)。
help_command_long_password=為已新增密碼來源的保護輸入密碼。
help_command_long_transfer=將你擁有的保護轉移給其他玩家。
help_command_long_trust=提示、列出或確認你的信任訪問列表變更。
help_command_long_unlock=解鎖物品。
